### ISSUE TITLE
Small error

### ISSUE THREAD

**Issue by illestmuzik** [GlenCFL/item-filter-code#24]
I'm getting a underlining error when i add (small relics, medium relics, large relics) to a 'show class.
Path of Exile source [control+f relics](https://pathofexile.gamepedia.com/Item_filter_guide)
Screenshot of error [here](https://i.imgur.com/tnT5Nkr.png)

If i'm doing something wrong please let me know. 
Goodluck p.s. i love this **item filter code!**

**Comment by GlenCFL** [comment]
I've added these missing item classes with v1.14.4 of the extension, which should be available shortly. Let me know if you run into any other issues with these relics.

These item classes are currently empty, so you might run into additional errors if you use these classes in conjunction with the `BaseType` rule within a single block. I'll fill out these classes at some point in the near future, but there's not much information readily available on them.
